In [5]:
import numpy as np
import os, sys
sys.path.append(os.path.abspath(os.path.join('../..')))

In [6]:
from utils.solvers import GaussElimination,BackSubstitution

In [7]:
A = np.array([[3,2,1],[1,4,-3],[-5,8,-4]], dtype=float)
b = np.array([10,0,-1], dtype=float)

In [8]:
A,b=GaussElimination(A,b)

In [9]:
x = BackSubstitution(A,b)

In [10]:
A

array([[ 3.        ,  2.        ,  1.        ],
       [ 0.        ,  3.33333333, -3.33333333],
       [ 0.        ,  0.        ,  9.        ]])

In [11]:
b

array([10.        , -3.33333333, 27.        ])

In [12]:
x

array([1., 2., 3.])